FROM python:3.12-alpine
WORKDIR /app
COPY /app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY /app .
EXPOSE 3000
CMD ["uvicorn", "main:app", "--host" ,"0.0.0.0" , "--port" , "3000"]