- hosts: web
  become: yes

  tasks:

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull latest Docker image
      docker_image:
        name: ghcr.io/nklshkumar/task-tracker-api:latest
        source: pull

    - name: Stop existing container
      shell: docker stop task-api || true

    - name: Remove existing container
      shell: docker rm task-api || true

    - name: Run new container
      shell: |
        docker run -d \
        --name task-api \
        -p 3000:3000 \
        ghcr.io/nklshkumar/task-tracker-api:latest